let weatherIcons = {
  "01d": "fa-sun",
  "01n": "fa-moon",
  "02d": "fa-cloud-sun",
  "02n": "fa-cloud-moon",
  "03d": "fa-cloud",
  "03n": "fa-cloud",
  "04d": "fa-cloud black-cloud",
  "04n": "fa-cloud black-cloud",
  "09d": "fa-cloud-showers-heavy",
  "09n": "fa-cloud-showers-heavy",
  "10d": "fa-cloud-sun-rain",
  "10n": "fa-cloud-moon-rain",
  "11d": "fa-cloud-bolt",
  "11n": "fa-cloud-bolt",
  "13d": "fa-snowflake",
  "13n": "fa-snowflake",
  "50d": "fa-smog",
  "50n": "fa-smog",
};

let infoIcons = {
  Clouds: "fa-cloud",
  "Feels Like": "fa-temperature-three-quarters",
  Humidity: "fa-droplet",
  Pressure: "fa-arrows-down-to-line",
  UVI: "fa-sun",
  Visibility: "fa-eye-low-vision",
  Wind: "fa-wind",
  "Wind Deg": "fa-location-arrow",
  Wind_Deg: "fa-location-arrow",
  Wind_Gust: "fa-tornado",
  Precipitation: "fa-cloud-showers-heavy",
};
let infoUnits = {
  metric: {
    Clouds: " %",
    "Feels Like": <sup> °C</sup>,
    Humidity: " %",
    Pressure: " hPa",
    UVI: "",
    Visibility: " m",
    Wind: " m/s",
    "Wind Deg": " °",
    Wind_Deg: " °",
    Wind_Gust: " m/s",
    Precipitation: " mm",
  },
  standard: {
    Clouds: " %",
    "Feels Like": <span> K</span>,
    Humidity: " %",
    Pressure: " hPa",
    UVI: "",
    Visibility: " m",
    Wind: " m/s",
    "Wind Deg": " °",
    Wind_Deg: " °",
    Wind_Gust: " m/s",
    Precipitation: " mm",
  },
  imperial: {
    Clouds: " %",
    "Feels Like": <sup> °F</sup>,
    Humidity: " %",
    Pressure: " hPa",
    UVI: "",
    Visibility: " m",
    Wind: " mi/h",
    "Wind Deg": " °",
    Wind_Deg: " °",
    Wind_Gust: " mi/h",
    Precipitation: " mm",
  },
};

export { weatherIcons, infoIcons, infoUnits };
